---
title: "Preprocessing script"
author: "Ashish"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: paper
---

Initialization
===
```{r, message=FALSE}
# devtools::install_github("amehtaSF/rsurveyutils")
library(rsurveyutils)
library(qualtRics)
library(here)
library(lubridate)
library(tidyverse)
library(tidylog)
theme_set(theme_bw())
```


Preprocessing
===

Read data
---
```{r}
filepath <- sprintf("%s/micronarrative_llm_vs_qualtrics_aug2024.csv", recent_date_dir(here("data/raw")))
df_file <- read_survey(here(filepath)) 

```


Read codebooks
---
```{r}
codebook_filepath <- "data/micronarrative_llm_vs_qualtrics_aug2024_codebook.xlsx"
codebook_vars <- readxl::read_excel(here(codebook_filepath), sheet="variables")

# codebook_values <- readxl::read_excel(here(codebook_filepath), sheet="values")
```

Process data
---
```{r}
df_raw <- df_file %>%
  janitor::clean_names() %>% 
  mutate(start_date = ymd_hms(start_date),
         end_date = ymd_hms(end_date)) %>% 
  # -- remove rows without prolific pid -- #
  filter(nchar(pid) == 24) %>%  
  # -- remove qualtrics erroneous header -- #
  # slice(-1) %>% 
  # -- add raw data file name -- #
  mutate(rawDataFile = filepath) %>% 
  # -- drop columns with all NA -- #
  select(-where(~all(is.na(.)))) %>% 
  # -- rename columns -- #
  codebook_renamer(names_from=codebook_vars$old_name,
                   names_to=codebook_vars$new_name) 
```

```{r}
df_recoded <- df_raw %>%
	# -- recode variables -- #
	codebook_recoder(var_regex=codebook_values$var_regex,
	                 values_from=codebook_values$old_value,
	                 values_to=codebook_values$new_value) %>% 
  # -- coding it so higher values refer to bot preference -- #
  mutate_at(vars(ends_with("compare")), ~ifelse(left_side == "bot", .*-1, .))
  
```


```{r}
df_proc <- df_recoded %>% 
  # -- remove columns with all NA -- #
  select_if(~!all(is.na(.))) %>% 
  filter(age <= 20) %>% 
  filter(progress == 100 & finished == TRUE) %>% 
  filter(use_survey == "Yes") %>%
  filter(use_survey_form == "Yes, I see my narrative and it is a valid challenging social media experience.") %>%
  filter(use_survey_bot == "Yes, I see my narrative and it is a valid challenging social media experience.") %>%
  filter(`ac_90-100` >= 90 & `ac_90-100` <= 100) %>% 
  filter(`ac_65-70` >= 65 & `ac_65-70` <= 70) %>% 
  filter(chatbot_summary != "" & !is.na(chatbot_summary)) %>% 
  select(-qualtrics_summary_157, -ip_address) 

# df_recoded %>% 
#   filter(chatbot_summary == "" | is.na(chatbot_summary)) %>%
#   view

# -- Check for duplicates -- #
df_proc %>% 
  group_by(pid) %>% 
  summarize(n = n()) %>%
  arrange(desc(n)) 
```


```{r, echo=FALSE}
# ------ End Preprocessing ------ #
# ----- Run all chunks above -----#
```

Prolific crediting
===
```{r}
df_proc %>% 
  pull(pid) %>% 
  cat(sep="\n")
```

```{r}
id = "66912d22f9cbca6c54eaeddf"
df_file %>% 
  filter(pid == id) %>%
  view

df_file %>% 
  filter(pid == id) %>% 
  select(Finished, Progress) 

id %in% df_proc$pid
```


```{r}

d <- df_recoded %>% 
  # -- remove columns with all NA -- #
  select_if(~!all(is.na(.))) %>% 
  filter(progress == 100 & finished == TRUE) %>% 
  filter(use_survey == "Yes") %>%
  filter(use_survey_form == "Yes, I see my narrative and it is a valid challenging social media experience.") %>%
  filter(use_survey_bot == "Yes, I see my narrative and it is a valid challenging social media experience.") %>%
  # filter(use_survey != "Yes" | use_survey_form != "Yes, I see my narrative and it is a valid challenging social media experience." | use_survey_bot != "Yes, I see my narrative and it is a valid challenging social media experience.") %>%
  # filter(`ac_90-100` >= 90 & `ac_90-100` <= 100) %>%
  # filter(`ac_65-70` >= 65 & `ac_65-70` <= 70) %>%
  filter(chatbot_summary != "" & !is.na(chatbot_summary)) %>%
  mutate(ac_1_pass = `ac_90-100` >= 90 & `ac_90-100` <= 100) %>% 
  mutate(ac_2_pass = `ac_65-70` >= 65 & `ac_65-70` <= 70)

d %>% 
  filter(xor(ac_1_pass, ac_2_pass)) %>% 
  pull(pid) %>% 
  cat(sep="\n")

d %>% 
  filter((!ac_1_pass | is.na(ac_1_pass)) & (!ac_2_pass | is.na(ac_2_pass))) %>% 
  pull(pid)



```




Export
===
```{r}
filepath_output <- paste0("data/proc/micronarrative_llm_vs_qualtrics_aug2024_proc.csv")
df_proc %>% 
  write_csv(here(filepath_output))
```



```{r}
df_proc$qualtrics_summary == df_proc$qualtrics_summary_157
```




Session Info
===
```{r}
sessionInfo()
```

